version: "3.7"
services:
  makeline-service:
    image: dejmartins/makeline-service:latest
    container_name: makeline-service
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - order-service
    environment:
      - ORDER_QUEUE_URI=amqp://username:password@rabbitmq:5672/
      - ORDER_QUEUE_HOSTNAME=rabbitmq
      - ORDER_QUEUE_USERNAME=username
      - ORDER_QUEUE_PASSWORD=password
      - ORDER_QUEUE_NAME=orders
      - ORDER_DB_URI=mongodb://mongo:27017
      - ORDER_DB_NAME=orders
      - ORDER_DB_COLLECTION_NAME=orderItems
    networks:
      - backend_services
  # virtual-customer:
  #   image: ramymohamed/virtual-customer-l8:latest
  #   container_name: 'virtual-customer'
  #   restart: always
  #   environment:
  #     - ORDER_SERVICE_URL=http://order-service:3000/
  #     - ORDERS_PER_HOUR=60
  #   networks:
  #     - backend_services
  #   depends_on:
  #     order-service:
  #       condition: service_healthy
networks:
  backend_services:
    driver: bridge